package com.chikere.jobai.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;

// NOTE: @Builder + @NoArgsConstructor + @AllArgsConstructor together is intentional.
// @Builder uses the explicit @AllArgsConstructor; @NoArgsConstructor lets Jackson
// deserialise via the no-arg constructor + setters (generated by @Data).
// If your Lombok version raises a duplicate-constructor error, remove @AllArgsConstructor
// — @Data + @NoArgsConstructor is enough for Jackson.
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PremiumReport {

    private String reportId;
    private String profession;
    private String mode;
    private double score;
    private String riskLevel;
    private LocalDateTime generatedAt;
    private GenerationMetrics generationMetrics;

    // ── Cover KPIs ─────────────────────────────────────────────────────────
    private String disruptionWindow;        // e.g. "5–8 yrs"
    private String adaptabilityPotential;   // "High" | "Medium" | "Low"

    // ── Section 01: Overview ────────────────────────────────────────────────
    private String executiveSummary;
    private String coreAdvice;

    // ── Section 02: Task Analysis ────────────────────────────────────────────
    private List<TaskRow> taskExposureMap;

    // ── Section 03: Timeline ─────────────────────────────────────────────────
    private List<TimelineEvent> timelineEvents;

    // ── Section 04: Skills Intelligence ──────────────────────────────────────
    private List<SkillCard> skillCards;

    // ── Section 05: Salary Intelligence ──────────────────────────────────────
    private String salaryTraditionalTitle;
    private String salaryTraditionalMedian;
    private String salaryTraditionalRange;
    private List<String> salaryTraditionalBullets;
    private String salaryAiTitle;
    private String salaryAiMedian;
    private String salaryAiRange;
    private List<String> salaryAiBullets;
    private String consultancyOpportunity;

    // ── Section 06: Adjacent Career Paths ────────────────────────────────────
    private List<TransitionRow> adjacentRoles;

    // ── Section 07: Action Plan ───────────────────────────────────────────────
    private List<String> thirtyDayPlan;
    private List<String> ninetyDayPlan;
    private List<String> yearPlan;

    // ── Section 08: Resources ─────────────────────────────────────────────────
    private List<ResourceCard> resources;

    // ── Retained fields (used by mock / not rendered in main template) ────────
    private String overallExposure;
    private String mostExposedArea;
    private String safestDirection;
    private String positioningAdvice;
    private List<String> aiStrengths;
    private List<String> humanAdvantages;
    private List<String> warningSigns;
    private List<ResilienceRow> resilienceScorecard;
    private List<CareerLevelRow> careerLevelAnalysis;
    private List<TrackRow> trackComparison;

    // ── Inner Classes ──────────────────────────────────────────────────────────

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class TaskRow {
        private String area;
        private int exposurePercent;      // 0–100; drives bar width directly
        private String exposure;          // "Very High" | "High" | "Moderate" | "Low" | "Very Low"
        private String timelineLabel;     // "Now" | "1–3 yrs" | "3–6 yrs" | "5–10 yrs" | "10+ yrs"
        private String reason;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class TimelineEvent {
        private String period;       // e.g. "Now — 2026"
        private String title;        // short bold headline
        private String description;  // 2–3 sentence paragraph
        private List<String> tags;   // tech / concept pill tags
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class SkillCard {
        private String icon;          // emoji
        private String name;          // skill name
        private String description;   // 2–3 sentences
        private String priority;      // "Critical" | "High" | "Medium"
        private String priorityNote;  // e.g. "demand is immediate and rising fast"
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ResourceCard {
        private String type;          // e.g. "COURSE · FREE" | "TOOL · TRY TODAY" | "BOOK" | "COMMUNITY"
        private String title;
        private String description;   // one sentence
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class TransitionRow {
        private String targetRole;
        private String salaryBand;
        private String aiResilience;
        private String transitionDifficulty;
        private String reason;
        private List<String> skillTags;   // e.g. ["LLM APIs", "RAG / Vector DBs", "Spring AI"]
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class CareerLevelRow {
        private String level;
        private String risk;
        private String commentary;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class TrackRow {
        private String track;
        private String exposure;
        private String reason;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ResilienceRow {
        private String factor;
        private String signal;
    }
}
