-- Baseline schema as of 2026-07-08, matching the JPA entities.
-- Portable SQL: runs on both H2 (dev) and PostgreSQL (production).

CREATE TABLE generated_reports (
    id                UUID NOT NULL,
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    profession        VARCHAR(255) NOT NULL,
    mode              VARCHAR(255) NOT NULL,
    generated_at      TIMESTAMP(6) WITH TIME ZONE,
    risk_score        DOUBLE PRECISION NOT NULL,
    risk_level        VARCHAR(255),
    payment_status    VARCHAR(20) NOT NULL,
    generation_status VARCHAR(20),
    stripe_session_id VARCHAR(255),
    request_hash      VARCHAR(64),
    expires_at        TIMESTAMP(6) WITH TIME ZONE,
    report_json       VARCHAR(1000000),
    PRIMARY KEY (id)
);

CREATE INDEX idx_reports_stripe_session ON generated_reports (stripe_session_id);
CREATE INDEX idx_reports_payment_expiry ON generated_reports (payment_status, expires_at);
CREATE INDEX idx_reports_request_hash ON generated_reports (request_hash);

CREATE TABLE analytics_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    event_type  VARCHAR(40) NOT NULL,
    visitor_id  VARCHAR(100),
    report_id   VARCHAR(40),
    profession  VARCHAR(300),
    risk_score  DOUBLE PRECISION,
    amount_cents BIGINT,
    currency    VARCHAR(10),
    duration_ms BIGINT,
    detail      VARCHAR(500),
    PRIMARY KEY (id)
);

CREATE INDEX idx_analytics_type_time ON analytics_events (event_type, occurred_at);
