-- Converges databases created by the old ddl-auto=update (pre-Flyway) with the V1 baseline.
-- Such databases were adopted via baseline-on-migrate, so V1 never ran against them and they
-- may carry drift: report_json as CLOB (old @Lob mapping) and, depending on when the app last
-- booted, missing columns/table/indexes. Every statement is a no-op on a fresh V1 database.
-- "SET DATA TYPE" is the SQL-standard form accepted by both H2 and PostgreSQL.

ALTER TABLE generated_reports ALTER COLUMN report_json SET DATA TYPE VARCHAR(1000000);
ALTER TABLE generated_reports ADD COLUMN IF NOT EXISTS generation_status VARCHAR(20);
ALTER TABLE generated_reports ADD COLUMN IF NOT EXISTS request_hash VARCHAR(64);

CREATE INDEX IF NOT EXISTS idx_reports_stripe_session ON generated_reports (stripe_session_id);
CREATE INDEX IF NOT EXISTS idx_reports_payment_expiry ON generated_reports (payment_status, expires_at);
CREATE INDEX IF NOT EXISTS idx_reports_request_hash ON generated_reports (request_hash);

CREATE TABLE IF NOT EXISTS analytics_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    event_type  VARCHAR(40) NOT NULL,
    visitor_id  VARCHAR(100),
    report_id   VARCHAR(40),
    profession  VARCHAR(300),
    risk_score  DOUBLE PRECISION,
    amount_cents BIGINT,
    currency    VARCHAR(10),
    duration_ms BIGINT,
    detail      VARCHAR(500),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_analytics_type_time ON analytics_events (event_type, occurred_at);
